################################### by Analisi #################################################
database:
  type: sqlite
  prefix: azgangs_

gang-settings:
  max-members-per-gang: 10
  enable-pvp-between-members: false
  max-name-length: 16
  min-name-length: 3

# Messaggi
messages:
  prefix: "&8[&6AZGangs&8] "
  gang-created: "&aLa tua gang &6%gangName% &a e' stata creata con successo!"
  gang-disbanded: "&cLa gang &6%gangName% &c e' stata sciolta."
  gang-renamed: "&aLa tua gang è stata rinominata in &6%newName%&a."
  invite-sent: "&aHai inviato un invito alla gang a &6%playerName%&a."
  missing-player-name: "&aPlayer non trovato."
  missing-gang-name: "&aGang non trovata."
  gang-not-found: "&aGang non trovata."
  invite-received: "&aSei stato invitato a unirti alla gang &6%gangName%&a. Usa /gang join per accettare."
  invite-accepted: "&a%playerName% si è unito alla tua gang."
  joined-gang: "&aTi sei unito alla gang &6%gangName%&a."
  gang-left: "&aHai lasciato la gang &6%gangName%&a. Se eri il proprietario, la gang è stata sciolta."
  no-permission: "&cNon hai il permesso per eseguire questo comando."
  already-in-gang: "&cSei già in una gang."
  not-in-gang: "&cNon sei in una gang."
  not-gang-owner: "&cSolo il proprietario della gang può eseguire questo comando."
  not-gang-member: "&cSolo i membri della gang possono eseguire questo comando."
  gang-full: "&cQuesta gang ha raggiunto il numero massimo di membri."
  player-not-found: "&cGiocatore non trovato o offline."
  player-already-in-gang: "&cQuesto giocatore è già in una gang."
  no-pending-invites: "&cNon hai inviti di gang in sospeso."
  invite-expired: "&cL'invito è scaduto."
  no-gangs: "&cNon sei in una gang."
  gang-name-taken: "&cEsiste già una gang con questo nome."
  gang-name-invalid: "&cNome della gang non valido. I nomi devono essere lunghi tra %min% e %max% caratteri e contenere solo lettere e numeri."
  gang-info-header: "&6===== &eInformazioni sulla Gang: &6%gangName% &6====="
  gang-info-owner: "&eProprietario: &f%owner%"
  gang-info-members: "&eMembri: &f%members%"
  gang-info-footer: "&6==========================================="
  gang-list-header: "&6===== &eLista delle Gang &6====="
  gang-list-entry: "&e%gangName% &7- &fProprietario: %owner%, Membri: %memberCount%"
  gang-list-footer: "&6==========================================="
  help-header: "&6===== &eGuida AZGangs &6===== by Analisi"
  help-footer: "&6==========================================="

help:
  create: "&e/gang create <nome> &7- Crea una nuova gang"
  disband: "&e/gang disband &7- Sciogli la tua gang"
  rename: "&e/gang rename <nome> &7- Rinomina la tua gang"
  invite: "&e/gang invite <giocatore> &7- Invita un giocatore nella tua gang"
  join: "&e/gang join &7- Unisciti a una gang in cui sei stato invitato"
  leave: "&e/gang leave &7- Lascia la tua attuale gang"
  info: "&e/gang info [gang] &7- Visualizza le informazioni su una gang"
  list: "&e/gang list &7- Elenco di tutte le gang"
  help: "&e/gang help &7- Visualizza questo messaggio di aiuto"

permissions:
  create: "azgangs.create"
  disband: "azgangs.disband"
  rename: "azgangs.rename"
  invite: "azgangs.invite"
  join: "azgangs.join"
  leave: "azgangs.leave"
  info: "azgangs.info"
  list: "azgangs.list"
  admin: "azgangs.admin"
