################################### by Analisi #################################################
database:
  type: sqlite
  prefix: azgangs_

gang-settings:
  max-members-per-gang: 10
  enable-pvp-between-members: false
  max-name-length: 16
  min-name-length: 3

# Messaggi
messages:
  prefix: "&8[&e&lAZGangs&8] &r"
  gang-created: "&a&lSuccesso! &fLa tua gang &e%gangName% &fe' stata creata con successo!"
  gang-disbanded: "&c&lAttenzione! &fLa gang &e%gangName% &fe' stata sciolta."
  gang-renamed: "&a&lSuccesso! &fLa tua gang e' stata rinominata in &e%newName%&f."
  invite-sent: "&b&lInfo! &fHai inviato un invito alla gang a &e%playerName%&f."
  missing-player-name: "&c&lErrore! &fPlayer non trovato."
  missing-gang-name: "&c&lErrore! &fGang non trovata."
  gang-not-found: "&c&lErrore! &fGang non trovata."
  invite-received: "&d&lInvito! &fSei stato invitato a unirti alla gang &e%gangName%&f. Usa &b/gang join &fper accettare."
  invite-accepted: "&a&lSuccesso! &e%playerName% &fsi e' unito alla tua gang."
  joined-gang: "&a&lSuccesso! &fTi sei unito alla gang &e%gangName%&f."
  gang-left: "&b&lInfo! &fHai lasciato la gang &e%gangName%&f. Se eri il proprietario, la gang e' stata sciolta."
  no-permission: "&4&lAccesso Negato! &fNon hai il permesso per eseguire questo comando."
  already-in-gang: "&c&lErrore! &fSei gia' in una gang."
  not-in-gang: "&c&lErrore! &fNon sei in una gang."
  not-gang-owner: "&c&lErrore! &fSolo il proprietario della gang puo' eseguire questo comando."
  not-gang-member: "&c&lErrore! &fSolo i membri della gang possono eseguire questo comando."
  gang-full: "&c&lErrore! &fQuesta gang ha raggiunto il numero massimo di membri."
  player-not-found: "&c&lErrore! &fGiocatore non trovato o offline."
  player-already-in-gang: "&c&lErrore! &fQuesto giocatore e' gia' in una gang."
  no-pending-invites: "&c&lErrore! &fNon hai inviti di gang in sospeso."
  invite-expired: "&c&lErrore! &fL'invito e' scaduto."
  no-gangs: "&c&lErrore! &fNon sei in una gang."
  gang-name-taken: "&c&lErrore! &fEsiste gia' una gang con questo nome."
  gang-name-invalid: "&c&lErrore! &fNome della gang non valido. I nomi devono essere lunghi tra %min% e %max% caratteri e contenere solo lettere e numeri."
  gang-info-header: "&6&l&nInformazioni sulla Gang: &e%gangName% &6&l"
  gang-info-owner: "&e&lProprietario: &f%owner%"
  gang-info-members: "&e&lMembri: &f%members%"
  gang-info-footer: "&6&l✦ &l======================= &6&l✦"
  gang-list-header: "&6&l✦ &e&l&nLista delle Gang &6&l✦"
  gang-list-entry: "&e%gangName% &7 &fProprietario: &b%owner%&f, Membri: &a%memberCount%"
  gang-list-footer: "&6&l======================= &6&l"
  help-header: "&6&lGuida AZGangs &6&l &d&oby Analisi"
  help-footer: "&6&l======================= &6&l"

help:
  create: "&e/gang create <nome> &7 &fCrea una nuova gang"
  disband: "&e/gang disband &7 &fSciogli la tua gang"
  rename: "&e/gang rename <nome> &7 &fRinomina la tua gang"
  invite: "&e/gang invite <giocatore> &7 &fInvita un giocatore nella tua gang"
  join: "&e/gang join &7 &fUnisciti a una gang in cui sei stato invitato"
  leave: "&e/gang leave &7 &fLascia la tua attuale gang"
  info: "&e/gang info [gang] &7 &fVisualizza le informazioni su una gang"
  list: "&e/gang list &7 &fElenco di tutte le gang"
  help: "&e/gang help &7 &fVisualizza questo messaggio di aiuto"

permissions:
  create: "azgangs.create"
  disband: "azgangs.disband"
  rename: "azgangs.rename"
  invite: "azgangs.invite"
  join: "azgangs.join"
  leave: "azgangs.leave"
  info: "azgangs.info"
  list: "azgangs.list"
  admin: "azgangs.admin"
