################################### by Analisi #################################################
database:
  type: "sqlite" # mysql or sqlite
  host: "localhost"
  port: 3306
  database: "azgangs"
  username: "root"
  password: "azplugins"
  table-prefix: "azgangs_"

gang-settings:
  max-members-per-gang: 10
  enable-pvp-between-members: false
  max-name-length: 16
  min-name-length: 3

# Messages
messages:
  prefix: "&8[&6AZGangs&8] "
  gang-created: "&aYour gang &6%gangName% &ahas been created successfully!"
  gang-disbanded: "&cGang &6%gangName% &chas been disbanded."
  gang-renamed: "&aYour gang has been renamed to &6%newName%&a."
  invite-sent: "&aYou have sent a gang invitation to &6%playerName%."
  invite-received: "&aYou have been invited to join gang &6%gangName%. Use /gang join to accept."
  invite-accepted: "&a%playerName% has joined your gang."
  joined-gang: "&aYou joined &6%gangName%"
  gang-left: "&aYou have left gang &6%gangName%. If you were the owner, the gang has been disbanded."
  no-permission: "&cYou don't have permission to execute this command."
  already-in-gang: "&cYou are already in a gang."
  not-in-gang: "&cYou are not in a gang."
  not-gang-owner: "&cOnly the gang owner can execute this command."
  not-gang-member: "&cOnly gang members can execute this command."
  gang-full: "&cThis gang has reached the maximum number of members."
  player-not-found: "&cPlayer not found or offline."
  player-already-in-gang: "&cThis player is already in a gang."
  no-pending-invites: "&cYou don't have any pending gang invitations."
  invite-expired: "&cThe invitation has expired."
  gang-name-taken: "&cA gang with this name already exists."
  gang-name-invalid: "&cInvalid gang name. Names must be %min%-%max% characters and contain only letters and numbers."
  gang-info-header: "&6===== &eGang Information: &6%gangName% &6====="
  gang-info-owner: "&eOwner: &f%owner%"
  gang-info-members: "&eMembers: &f%members%"
  gang-info-footer: "&6==========================================="
  gang-list-header: "&6===== &eGang List &6====="
  gang-list-entry: "&e%gangName% &7- &fOwner: %owner%, Members: %memberCount%"
  gang-list-footer: "&6==========================================="
  help-header: "&6===== &eAZGangs Help &6===== by Analisi"
  help-footer: "&6==========================================="


help:
  create: "&e/gang create <name> &7- Create a new gang"
  disband: "&e/gang disband &7- Disband your gang"
  rename: "&e/gang rename <name> &7- Rename your gang"
  invite: "&e/gang invite <player> &7- Invite a player to your gang"
  join: "&e/gang join &7- Join a gang you've been invited to"
  leave: "&e/gang leave &7- Leave your current gang"
  info: "&e/gang info [gang] &7- Display information about a gang"
  list: "&e/gang list &7- List all gangs"
  help: "&e/gang help &7- Display this help message"


permissions:
  create: "azgangs.create"
  disband: "azgangs.disband"
  rename: "azgangs.rename"
  invite: "azgangs.invite"
  join: "azgangs.join"
  leave: "azgangs.leave"
  info: "azgangs.info"
  list: "azgangs.list"
  admin: "azgangs.admin"