name: AZGangs
version: 1.0
main: it.quick.azgangs.AZGangs
author: Analisi
description: 1.8 Gangs plugin by Analisi 
api-version: 1.8
softdepend: [PlaceholderAPI]
commands:
  gang:
    description: Comando principale, esegui /gang help.
    aliases: [gangs]
permissions:
  azgang.*:
    description: Dai l'accesso Full perms ai comandi del plugin.
    default: op